import argparse
import json

from email.message import EmailMessage

NOTE = "output/weekly_note.md"
STATS = "data/theme_stats.json"
TXT_OUT = "output/email_draft.txt"
EML_OUT = "output/email_draft.eml"

DEFAULT_TO = "you@example.com"
FROM = "review-pulse@groww.internal"

FOOTER = (
    "Auto-generated by the Groww Review Pulse pipeline. "
    "No PII: emails, phone numbers, UPI IDs, and PANs are redacted "
    "before generation."
)


def load_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read().strip()


def load_stats():
    with open(STATS) as f:
        return json.load(f)


def build_intro(stats):
    total = stats["total_reviews"]
    start = stats["date_range"]["start"]
    end = stats["date_range"]["end"]
    return (
        "Hey team,\n"
        "Here is this week's review pulse, compiled from "
        f"{total} App Store and Play Store reviews covering {start} to {end}. "
        "It covers the top themes, verbatim quotes from users, and suggested "
        "next actions."
    )


def build_body(stats, note):
    return "\n\n".join([build_intro(stats), note, FOOTER])


def write_txt(to_addr, subject, body):
    with open(TXT_OUT, "w", encoding="utf-8") as f:
        f.write(f"To: {to_addr}\n\n")
        f.write(f"Subject: {subject}\n\n")
        f.write(body + "\n")


def write_eml(to_addr, subject, body):
    msg = EmailMessage()
    msg["From"] = FROM
    msg["To"] = to_addr
    msg["Subject"] = subject
    msg.set_content(body)
    with open(EML_OUT, "wb") as f:
        f.write(msg.as_bytes())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--to", default=DEFAULT_TO)
    args = parser.parse_args()

    stats = load_stats()
    note = load_text(NOTE)
    subject = f"Groww Weekly Review Pulse — {stats['generated_at']}"
    body = build_body(stats, note)

    write_txt(args.to, subject, body)
    write_eml(args.to, subject, body)

    print(f"wrote {TXT_OUT} and {EML_OUT}")
    print(f"recipient: {args.to}")
    print(f"subject: {subject}")


if __name__ == "__main__":
    main()